### ISSUE TITLE
Newly added foreign element don't display and many to many relation couldn't add item

### ISSUE THREAD

**Issue by gahan9** [asyncee/django-easy-select2#42] opened 2018-04-08 09:58 UTC
I have configured django easy select according to document, it's working fine but when I add new item to foreign key field it's actually selected but it isn't displayed in UI that whatanelement selected. after adding new element from pop up any element I choose it will only display None.

For many to many field it doesn't add item. 

python==3.5.2
Django==2.0.2
django-easy-select2==1.3.4

----
For now I have to either refresh page or press save and continue editing so that I can add/select item(s) after newly added item.

**Comment by asyncee** [comment] 2018-04-08 12:33
Hi! Please, try to use latest version, which is 1.4.

**Comment by gahan9** [comment] 2018-04-08 12:41
I have updated to latest version 1.4 as you suggested, but still default `---` showed while adding and for edit it displays previously selected field, however many to many field is working if i click same element twice.

**Comment by gauravv7** [comment] 2018-04-08 19:03
@gahan9 with all such information give, I tried setting up a sample project ([link](https://github.com/gauravv7/easy_select_1.4)) which you can use freely to match the problem you are getting (python version its made with is Python 3.4.3 (default, Nov 28 2017, 16:41:13)).

I am afraid I would be needing a little more information about your project's usage of easy_select2. Can you please share the plugin's usage snippets?

**Comment by gahan9** [comment] 2018-04-09 11:41
@gauravv7 sample project is perfect and I have used easy_select2 in same way; here's the [link](https://streamable.com/rn6y0) to stream for the same project. It's working but it doesn't displays what is selected

**Comment by asyncee** [comment] 2018-04-09 11:43
@gauravv7 i think the problem could be solved by just re-rendering select2. Looks like some internal selection state is persisted, but the view is not updated.

**Comment by asyncee** [comment] 2018-04-13 16:01
@gahan9 we can not reproduce this problem using easy-select2 1.4.0.

I have just tested it and found out that version 1.3.4 is buggy, but 1.4.0 is not.

I'm closing this issue, because problem is not reproduced on django==2.0.4 and django-easy-select2==1.4.0.

If you still can reproduce it with provided sample project, please, feel free to reopen, but make sure you have provided detailed information.

Thanks!

**Closed by asyncee** 2018-04-13 16:01 UTC
